'use client';

import Link from 'next/link';
import { ExecutionStatusPanel } from '@/components/ExecutionStatusPanel';
import { readGeneratedReport } from '@/components/runtime';
import { AGENT_LABELS, AgentType, getAgentAsset } from '@/lib/demoReport';
import { GeneratedAsset, GeneratedReport } from '@/lib/startupclaw';
import { useEffect, useState } from 'react';

function isAgentType(value: string | undefined): value is AgentType {
  return ['research', 'validation', 'messaging', 'offer', 'gtm', 'killscale', 'creative', 'content', 'community', 'retention', 'ops'].includes(value ?? '');
}

export function AssetPageClient({ requestedAgent }: { requestedAgent?: string }) {
  const agent: AgentType = isAgentType(requestedAgent) ? requestedAgent : 'validation';
  const [generatedReport] = useState<GeneratedReport | null>(() => readGeneratedReport<GeneratedReport>());
  const [asset, setAsset] = useState<GeneratedAsset | null>(null);
  const [loading, setLoading] = useState(Boolean(generatedReport));

  useEffect(() => {
    let cancelled = false;
    async function run() {
      if (!generatedReport) {
        const fallback = getAgentAsset(agent);
        setAsset({ ...fallback, whyItMatters: `This ${AGENT_LABELS[agent]} output shows the kind of next work startupClaw can produce.`, agent, source: 'fallback' });
        setLoading(false);
        return;
      }
      setLoading(true);
      try {
        const response = await fetch('/api/asset', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ agent, report: generatedReport }),
        });
        const data = await response.json();
        if (!cancelled) {
          if (!response.ok || !data.asset) throw new Error(data.error || 'Failed to generate asset');
          setAsset(data.asset);
        }
      } catch {
        if (!cancelled) {
          const fallback = getAgentAsset(agent);
          setAsset({ ...fallback, whyItMatters: `This ${AGENT_LABELS[agent]} output helps ${generatedReport.startupName} move from diagnosis to execution.`, agent, source: 'fallback' });
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    void run();
    return () => { cancelled = true; };
  }, [agent, generatedReport]);

  const title = loading ? 'Generating asset...' : asset?.title ?? 'Generated Asset';

  return (
    <main className="mx-auto max-w-4xl px-6 py-12">
      <p className="text-xs font-bold uppercase tracking-[0.2em] text-zinc-500">startupClaw asset</p>
      <h1 className="mt-3 text-4xl font-bold tracking-tight text-zinc-950">{title}</h1>
      <p className="mt-3 text-lg text-zinc-600">Generated by the {AGENT_LABELS[agent]} as an example of execution-oriented output.</p>
      {asset?.source ? <p className="mt-2 text-sm text-zinc-500">Source: {asset.source === 'llm' ? 'LLM-generated' : 'Fallback logic'}</p> : null}

      <div className="mt-8">
        <ExecutionStatusPanel
          title="Current asset generation status"
          level={loading ? 'working' : asset?.source === 'llm' ? 'ready' : 'working'}
          canDoNow={[
            'Generate a concrete work package from the recommended expert agent',
            'Show what output is ready to use immediately',
            'Explain whether the output came from full generation or fallback logic',
          ]}
          aiDoing={[
            loading ? 'Generating the next useful work package now' : 'Prepared the next work package for review and use',
            'Packaging the report into an execution-ready asset',
            'Keeping the output tied to the diagnosed bottleneck',
          ]}
          userNeeded={[
            'Review and adapt the output if you want tighter real-world fit',
            'Provide external tool access only if later execution depends on missing integrations',
            'Use or export the asset to start the next step',
          ]}
        />
      </div>

      <section className="mt-8 rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm">
        {loading ? <p className="text-zinc-600">Thinking through the next work package...</p> : (
          <ul className="list-disc space-y-3 pl-5 text-zinc-700">
            {asset?.body.map((item) => <li key={item}>{item}</li>)}
          </ul>
        )}
      </section>

      <section className="mt-6 rounded-2xl border border-black bg-zinc-950 p-6 text-white">
        <p className="text-sm uppercase tracking-[0.2em] text-zinc-400">Why this asset matters</p>
        <p className="mt-3 max-w-2xl text-zinc-300">{loading ? 'startupClaw is turning the report into a usable work package.' : asset?.whyItMatters}</p>
        <div className="mt-5 flex flex-wrap gap-3">
          <Link href="/agents" className="rounded-xl bg-white px-5 py-3 font-semibold text-black">Back to agents</Link>
          <Link href="/report?generated=1" className="rounded-xl border border-zinc-700 px-5 py-3 font-semibold text-white">Back to report</Link>
        </div>
      </section>
    </main>
  );
}
